### ISSUE TITLE
check-in

### ISSUE THREAD

**Issue by XxKikoxX** [XxKikoxX/capstone-project#2]
# Title: check-in

## Value Proposition

- As a user
- I want to check-in my clothes
- in order to see all informations about my check-in.

## Description

![Bildschirm­foto 2023-03-28 um 11 59 47](https://user-images.githubusercontent.com/123958222/228201311-2bd590fb-7357-4688-95a3-86553816493a.png)

## Acceptance criteria

- [x] add app logo
- [x] add a inputfield
- [x] entering a different Bügel-Id displays a different information page (belonging to the id).
- [x] add a infotext under the inpufield
- [x] a check-out button on the information-page (that bring you back to your fresh check-in)

 ## Tasks

- [x] bring the logo on the page
- [x] built a inputfield for the "Bügel/id" with a placeholder "z.b ...567139"
- [x] built a infotext under the inputfield of "Bügel/id" that helps the user to find the information for the inputfield above
- [x] build a check-in button
- [x] build a check-out button which brings the user back to a fresh (empty) check-in page

**Comment by PReichetanz** [comment]
Hi Kevin,

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## General

## Value Proposition

## Description
- The second screen looks like it should not be really visible, but this is not the case, right? 
- Please remove the heading "Aktueller Aufenthalt" and the hamburger menu if it's not part of this story.
What are the symbols on the bottom, a navigation? If so, please remove it because you don't use / build it.


## Acceptance Criteria
You don't need to write down here what's already visible in the scribble. You should rather add
- Entering a different Bügel-Id displays a different information page (belonging to the id).

## Tasks
You could remind yourself how to handle the page changes:
- use `next/link` to link the pages (check-in and check-out button)
- What about tests?
